spring:
  datasource:
    url: jdbc:h2:mem:appdb
    schema: classpath:db/h2/schema.sql
    data: classpath:db/h2/data.sql
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false

security:
  jwt:
    issuer: angular-spring-jwt
    header: Authorization
    expires_in: 600 # 10 minutes
    secret: queenvictoria
    cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG
